#page title
page_title                                :  Away for Twitter                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1580040911                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/away-for-twitter/id1580040911?itsct=apps_box_promote_link&itscg=30200                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : /press-kit                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/away/app_icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Away for Twitter                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The first Twitter client to help you use Twitter less, not more.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Marina Gornostaeva                                
your_link                                 : https://hybridcattt.com                     
your_city                                 : Copenhagen 🇩🇰                                
email_address                             : awayfortwitter@hybridcattt.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : get_away_app
github_username                           : hybridcattt
youtube_username                          :


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : New messages
    emoji                                 : 💬
    description                           : Read your newest messages, decide if they are worth opening Twitter for

  - title                                 : Stats for recent tweets
    emoji                                 : 💯
    description                           : Check replies to your tweets, as well as the number of quotes, retweets and likes

  - title                                 : Number of followers
    emoji                                 : 👯‍♀️
    description                           : Know if your account is growing. Rounded or precise - choose how much you care

  - title                                 : Days since last tweeted
    emoji                                 : 📆
    description                           : Know if it's been a while since you posted to keep an active profile

  - title                                 : Use with any Twitter app
    emoji                                 : ↗️
    description                           : Deep links available to your favorite Twitter app or browser

  - title                                 : Multiple accounts
    emoji                                 : 👥
    description                           : Monitor multiple Twitter accounts in one app

features2Title                           : You choose what's important

features2                                 :

  - title                                 : Choose the stats 
    emoji                                 : 🙈
    description                           : Don't care about likes? Got it. Don't want the exact follower count? Sure.

  - title                                 : All data stays on device
    emoji                                 : 🕵️‍♀️
    description                           : Data downloaded from Twitter servers stays local. No one has access to your data, except you

  - title                                 : No push notifications
    emoji                                 : 📵
    description                           : You decide, when it's time to engage


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : "assets/anthony-tuil-lS_eDob6DDg-unsplash.jpg"                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
