# https://docs.netlify.com/configure-builds/file-based-configuration/
  
[[headers]]
  for = "/assets/*"
  [headers.values]
    #  Multi-value headers are expressed with multi-line strings
	  cache-control= "max-age=604800" # 7 days

[[redirects]]
  from = "/press-kit"
  to = "https://impresskit.net/away"
  status = 302

[[redirects]]
  from = "/app_preflight*"
  to = "/api/app_preflight_none.json/:splat"
  status = 200

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]

  # You can mark some check as todo, which will execute the check, but allow failures.
  # todoPatterns is an array of strings you can match against failing reports
  todoPatterns = ["/press-kit"]