# https://docs.netlify.com/configure-builds/file-based-configuration/
  
[[headers]]
  for = "/assets/*"
  [headers.values]
    #  Multi-value headers are expressed with multi-line strings
	cache-control= "max-age=604800" # 7 days
